version = 1
SPDX-PackageName = "Continuous Traceability Monitor (CTM)"
SPDX-PackageDownloadLocation = "https://github.com/SAP/quality-continuous-traceability-monitor"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2018-2021 SAP SE or an SAP affiliate company and Continuous Traceability Monitor (CTM) contributors"
SPDX-License-Identifier = "Apache-2.0"
