version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: cimg/go:1.13.15
        
    working_directory: $HOME/go/src/github.com/SAP/quality-continuous-traceability-monitor

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout       
      - run: mkdir -p $TEST_RESULTS

      - restore_cache:
          keys:
            - v1-pkg-cache

      # Get JUnit XML formater
      - run: go get github.com/jstemmer/go-junit-report

      - run:
          name: Run unit tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make test | tee ${TEST_RESULTS}/go-test.out

      - run: make build-linux
      - run: make build-windows

      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"            

      # Store artifacts and test results
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_artifacts:
          path: ./workdir
          destination: artifacts

      - store_test_results:
          path: /tmp/test-results
